name: Terraform Pipeline with Apply (GCP)

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: Terraform Workflow
    runs-on: ubuntu-latest
    env:
      GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Set up Google Cloud credentials
        run: echo "${{ secrets.GCP_CREDENTIALS }}" > "$HOME/secret-key.json"

      - name: Terraform Format Check
        run: terraform fmt -check -recursive
        working-directory: vpc_usage

      - name: Terraform Init
        run: terraform init
        working-directory: vpc_usage
        env:
          GOOGLE_APPLICATION_CREDENTIALS: $HOME/secret-key.json

      - name: Terraform Validate
        run: terraform validate
        working-directory: vpc_usage
        env:
          GOOGLE_APPLICATION_CREDENTIALS: $HOME/secret-key.json

      - name: Terraform Plan
        run: terraform plan
        working-directory: vpc_usage
        env:
          GOOGLE_APPLICATION_CREDENTIALS: $HOME/secret-key.json

      - name: "Terraform Apply (CAUTION: Will Create Resources)"
        run: terraform apply -auto-approve
        working-directory: vpc_usage
        env:
          GOOGLE_APPLICATION_CREDENTIALS: $HOME/secret-key.json