name: My First Terraform Pipeline

on:
    push:
        branches:
            - main # Runs only when you push to main branch

jobs:
    terraform:
        name: Terraform workflow
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup terraform
              uses: hashicorp/setup-terraform@v3

            - name: Terraform Format Check
              run: terraform fmt -check -recursive

            - name: Terraform Init
              run: terraform init

            - name: Terraform Validate
              run: terraform validate

            - name: Terraform Plan
              run: terraform plan